### ISSUE TITLE
 Research Travel management options for MozFest 2015 #343 

### ISSUE THREAD

**Issue by Saallen** [Saallen/MozFestroadmap#10]
Working with becky @quakpac to
*evaluate the potential of working with Egensia w MozFest specific account for flights
- short list 3 other possible agents for travel management
  *\* @saallen to evaluate in-house option of accommodation management through hotel direct bookings and contract negotiations

**Comment by Saallen** [comment]
Making a short list to start researching
Possible agencies we can investigate
- shworldwide's travel agent
- <s>Egencia</s>
- http://travelport.com/
- Connossieur Travel

Online  software tools
*[Joombookingmbooking](http://joombooking.com/services/travel-booking-solution)(opensource)
*[Open conference Ware](http://openconferenceware.org/) (opensource)
*[Meetingmax](http://meetingmax.cc/cvb/) (used this year by sxsw)

Anymore to add to our research @quakpac?

**Comment by quakpac** [comment]
I spoke with Angela about Egencia: sounds like working with them wouldn't be the best option given how we're currently set up with Egencia (our account is a branch of the MoCo account, so adding another account to it would be bad). Also given all the issues we've been having with Egencia lately, it would be better to avoid them.

**Comment by Saallen** [comment]
:+1:

**Comment by Saallen** [comment]
Meeting with Travel Leaders - who are in the same building as MozLdn.

**Comment by Saallen** [comment]
Talking to Tzell Operators who work from 101 St Martins lane

**Comment by Saallen** [comment]
Travel stipends allocated with monetary value this year so no booking of flights
