### ISSUE TITLE
Create a timeline for all MozFest website pages

### ISSUE THREAD

**Issue by Saallen** [Saallen/MozFestroadmap#11]
Timeline needed for publishing of individual MozFest pages
Then we can see where and when additional resources will be needed

Driver @saallen
Consult @edrushka
Feedback @Roberto-Cruz

**Comment by edrushka** [comment]
By "all MozFest website pages" do you mean updates to the main CTA, e.g.
Save the date
Submit a proposal
Buy a ticket
etc.?

**Comment by edrushka** [comment]
cc @mmmavis @sabrinang

**Comment by Saallen** [comment]
Yes. Call for Proposals timeline on the website
I will map it all out and then we can refine

**Comment by Saallen** [comment]
Created this [ timeline ](https://docs.google.com/a/mozillafoundation.org/spreadsheets/d/1EsdWh3UgJWs21EBzNIKJh0XYYZDYcRPGcgMIxv0NGwk/edit#gid=)
Highlighted dates for when info should be visible on the website @edrushka @Roberto-Cruz 
Can cross reference with @Roberto-Cruz [doc](https://docs.google.com/a/mozillafoundation.org/file/d/0B_B9-Ny1xBaRUXNnRW5STWVLcFE/edit)

**Comment by Saallen** [comment]
Do we need to spend more time on this timeline and factor in dev and design time or will this be done by the other teams now?

**Comment by edrushka** [comment]
When I chatted with Scott, this timeline seemed plausible (the one on the ErikaD tab). I think it's critical to decide the platform ASAP (wordpress or Node) or we'll lose a valuable build time.

**Comment by Saallen** [comment]
I am wondering now with the new teams how do we elevate website changes- ie last year we made bugs. Is there any clarity on the pathway for this year?

**Comment by edrushka** [comment]
I think there are 2 parts to this answer. First, I dug out all the old site bugs: https://bugzilla.mozilla.org/buglist.cgi?query_format=specific&order=relevance%20desc&bug_status=__closed__&content=MozFest%202014%20Site&comments=0&list_id=12106047 It seems like the majority of the changes needed last year would be built into the new site from Day 1 (meaning there should be significantly fewer changes requested in 2015).

As for the changes that are required, we are currently using the TPS system. Theoretically, if the organization commits to doing MozFest, TPS should elevate the changes (which will need to be filed on Github) and ensure they happen in a timely manner. The TPS/heartbeat system is currently evolving to address smaller tasks like site tweaks, and I have confidence that we'll have a way to prioritize the necessary changes.

**Comment by Saallen** [comment]
This mean that tweeks will take a minimum of two weeks as TPS meet every two weeks?
If an change is required, then added to github, will the change have to go before TPS before it is handled by a dev?
Adding @thornet into the convo

**Comment by edrushka** [comment]
TPS is meeting on Monday to devise a system for these smaller, more time sensitive tasks.
