### ISSUE TITLE
Shortlist registration platforms for Mozfest 

### ISSUE THREAD

**Issue by Saallen** [Saallen/MozFestroadmap#12]
First meeting with Eventrbrite

**Comment by Saallen** [comment]
@quakpac adding you in on this and will build it out tomorrow :)

**Comment by Saallen** [comment]
- [x] Need a shortlist of potential registration platforms
- [ ] Shortlist MoFo parties interested in making final decision
- [x] Set up meetings with potential list
- [ ] Feedback from invested parties
- [ ] Choose platform

**Comment by quakpac** [comment]
- [ ] foiwefoniwef
- [ ] oijweofijwef

**Comment by quakpac** [comment]
-[ ] thing

**Comment by quakpac** [comment]
- [ ] thing

**Comment by quakpac** [comment]
Sarah - were you trying to make checkboxes? Apparently you need to write     - [ ] Choose Platform

**Comment by quakpac** [comment]
- [ ] thing

**Comment by quakpac** [comment]
I've reached out to Universe about ticketing: https://www.universe.com/home. Lucy found them by chance, and it looks like they have special non-profit pricing. I'll report back when I've got more info, but so far it appears their features are very similar to Eventbrite.

**Comment by Saallen** [comment]
@thornet send me a link for this rego platform https://ti.to/
I just signed up using my email address and the passwork M0zfest6 if you want to check it out. Trying to get us a meeting for next week @quakpac

**Comment by quakpac** [comment]
Here is the list of capabilities we're looking for in a registration platform:
- multiple tickets for different groups, all available on the same purchasing page
- tax receipt/confirmation emailed as soon as someone registers
- an easily downloadable list of participants; the ability to make name tags
- the option of having the platform take care of payments, and then forward the money to Mozilla
- clear fee structure (per ticket; one lump fee, etc)
- ensure they can add VAT to the ticket price
- we'd like to be able pull finance-related reports
- clear process on issuing refunds
- easy check in process at event (scanning?)

**Comment by Saallen** [comment]
:boom: @quakpac Nice work.

**Comment by Saallen** [comment]
Quick outlines of each platform reviewed thus far.

[ Eventbrite ](https://www.eventbrite.com/) platform
Multifunctional platform compatible CRM and API integration functionaility for MozFest Website.
No cost if the tickets are free 
Standard fee: 2.5 % of registration value plus £0.65 for priced tickets
Or 3.5% if Eventbrite process the fees for us

 [ Amiando events ](http://www.amiando.com/)
Multifunctional platform compatible CRM and API integration functionaility for MozFest Website.
Costs 5.9% per ticket sold, plus and additional .89p pet ticket
Free tickets cost .89p per ticket

[ Tit.o ](https://ti.to/)
Smaller company than the two above but has worked with alot of smaller tech festivals such as jsconf as well as the massive events such as Web Summitt in Dublin last year.
Tickets can be puchased and rego info filled in later, simplier platform than those above.
Costs 3% per ticket sold- or pay €99 upfront and .90p per ticket

**Comment by Saallen** [comment]
Ti.to being examined by MoCo legal and date protection team
