### ISSUE TITLE
Venue: Space hire

### ISSUE THREAD

**Issue by Saallen** [Saallen/MozFestroadmap#22]
- [x] Map predicted space use
- [x] Outline of days/hours
- [x] Prototyping usage
- [x]  Negotiate contract
- [ ]  Legal review
- [ ] Sign Contract

**Comment by Saallen** [comment]
- [ ] Sign up for Ravensbourne students via volunteer form
- [ ] sign up for students to attend

**Comment by HolaHewitt** [comment]
Is there a contract ready for signature yet?   The $ is large so we will need to have Mark sign and his availability is dependent on his travel.  Let me know what I can do to help
