### ISSUE TITLE
Build recommendation doc on for Youth Zone management

### ISSUE THREAD

**Issue by Saallen** [Saallen/MozFestroadmap#32]
@marcwalsh will create a DBS doc recommendation from previous events and partners.

Examining at
- [x]  Parents must remain  with xxx ages and younger
- [x]  How to manage lost kids in the building
- [x] How to create a safe and comfortable area
- [x] Who must be DBS checked?
- [x] List of potential DBS checks available
- [x] Managing curated tours

**Comment by marcwalsh** [comment]
Document shared on Google Drive.

**Comment by marcwalsh-zz** [comment]
Document shared on Google Drive.

**Comment by marcwalsh-zz** [comment]
Complete
