### ISSUE TITLE
Supplier- Feast

### ISSUE THREAD

**Issue by Saallen** [Saallen/MozFestroadmap#36]
Feast will run catering for the festival weekend
- [ ] Logistical info
  - [ ]  location of catering
  - [ ] set up times
  - [ ] manage voltage w Raves
- [ ]  Confirm menues  
- [ ] sign contract
- [ ]  receive RA
- [ ] Submit Invoice

**Comment by HolaHewitt** [comment]
Please let me know how I can facilitate the contract and deposit part of this.
