### ISSUE TITLE
DBS Checks for Youth Zone

### ISSUE THREAD

**Issue by marcwalsh-zz** [Saallen/MozFestroadmap#50]
- [ ] Contract external company for online checking.
- [ ] Gather inital regsitration information
  - Full Legal Name
  - Date of Birth
  - Email Address
- [ ] Perform ID Checks
- [ ] Perform Additional Information Check

Process can take up to 30 days, but can be as short as 7 days or as long as 70+.

**Comment by HolaHewitt** [comment]
This is Pamela-Adding myself to a few of these issues.
Do we need a contract for DBS?

**Comment by marcwalsh-zz** [comment]
The contract wouldn't be with DBS but a third party would is able to carry out and countersign the checks on our behalf.

**Comment by HolaHewitt** [comment]
cool.  Hi Marc, nice to meet you.  :)  With any suppliers that need payment we have to do a contract.  Its pretty standard and simple.  The  delay comes in getting signatures on our end.  Only Mark and Angela can sign so we try and give us a few days to get them.  Please let me know how I can help in anyway.
